[package]
name = "deferred_shading"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Oleksandr Zaharevskyi <oleksandr.z@obox.systems>",
]

[dependencies]
glam = { version = "0.29.1", features = ['bytemuck'] }
tobj = { workspace = true }
bytemuck = { workspace = true }
minwebgl = { workspace = true }
web-sys = { workspace = true, features = [
  'HtmlImageElement',
  'WebGlFramebuffer',
  'WebGlRenderbuffer',
  'WebGlTexture',
] }
