[package]
name = "minwebgl_space_partition"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Avramenko Yevhenii <yevhenii.av@obox.systems>"
]
license = "MIT"

[lints]
workspace = true

[dependencies]
line_tools = { workspace = true }
minwebgl = { workspace = true, features = [ "math" ] }
serde = { workspace = true, features = [ "derive" ] }
serde-wasm-bindgen = { workspace = true }
browser_input = { workspace = true }
#spart = { workspace = true }
spart = { git = "file:///home/jeki/projects/rust/spart", branch = "log_feature" }
fastrand = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
  'PointerEvent',
]
