[package]
name = "browser_log"
version = "0.3.0"
edition = "2021"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"
rust-version = "1.81.0"
repository = "https://github.com/Wandalen/cg_tools"
description = "Utility to log in wasm/browser"
readme = "readme.md"
keywords = ["wasm"]

[lints]
workspace = true

[dependencies]

wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
  'console',
]}
log = { workspace = true, features = [ "std" ] }
mod_interface = { workspace = true }

# xxx : introduce features
# xxx : introduce features: enabled, default, full

