[package]
name = "mdmath_ia"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"
repository = "https://github.com/Wandalen/cg_tools"
readme = "readme.md"
description = "Multidimensional math."
keywords = ["math", "cg"]

[lints]
workspace = true

# xxx : introduce features
# xxx : introduce features: enabled, default, full

[dependencies]
mod_interface = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }
