[package]
name = "mdmath_core"
version = "0.3.0"
edition = "2021"
rust-version = "1.75.0"
authors = ["Kostiantyn Mysnyk <wandalen@obox.systems>"]
license = "MIT"
repository = "https://github.com/Wandalen/cgtools"
homepage = "https://github.com/Wandalen/cgtools/tree/master/module/math/mdmath_core"
documentation = "https://docs.rs/mdmath_core"
readme = "readme.md"
description = "Core multidimensional mathematics library with fundamental types, traits, and operations"
keywords = ["math", "multidimensional", "linear-algebra", "traits", "core"]
categories = ["mathematics", "no-std", "science", "api-bindings"]
include = [
    "src/**/*",
    "tests/**/*",
    "Cargo.toml",
    "readme.md",
    "license*",
    "changelog*",
]

[lints]
workspace = true

# [lints.rust]
# # Encourages documentation for public items.
# missing_docs = "warn" # qqq : uncomment please
# # Suggests implementing Debug for public types.
# missing_debug_implementations = "warn" # qqq : uncomment please

[features]

enabled = [
  "dep:mod_interface",
  "dep:clone_dyn_types",
]
default = [
  "enabled",
]
full = [
  "default",
  "index",
  "nd",
  "arithmetics",
  "general",
]

index = [ "dep:ndarray" ]
nd = [ "dep:ndarray" ]
float = [ "nd", "dep:num-traits" ]
approx = [ "float", "dep:approx" ]
arithmetics = [ "float" ]
general = []

[dependencies]
mod_interface = { workspace = true, optional = true }
clone_dyn_types = { workspace = true, optional = true }
ndarray = { workspace = true, optional = true, features = [] }
approx = { workspace = true, optional = true, features = [] }
num-traits = { workspace = true, optional = true, features = [] }

[dev-dependencies]
test_tools = { workspace = true }

# Metadata for crates.io
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
default-target = "x86_64-unknown-linux-gnu"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "wasm32-unknown-unknown",
]

# Cargo.toml maintenance metadata
[package.metadata.release]
pre-release-replacements = [
    { file = "readme.md", search = "mdmath_core = \"[0-9.]+\"", replace = "mdmath_core = \"{{version}}\"" },
    { file = "changelog.md", search = "## Unreleased", replace = "## Unreleased\n\n## {{version}} - {{date}}" },
]
