[package]
name = "embroidery_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
mod_interface = { workspace = true }
byteorder = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true
