[package]
name = "raycaster"
version = "0.1.0"
edition = "2021"

[dependencies]
minwebgl = { workspace = true }
tobj = { workspace = true, default-features = false, features = ['async'] }
web-sys = { workspace = true, features = [
  'KeyboardEvent',
  'WebGlTexture',
  'HtmlImageElement',
] }
