[package]
name = "browser_tools"
version = "0.2.0"
edition = "2021"
rust-version = "1.81.0"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"
repository = "https://github.com/Wandalen/cg_tools"
description = "Utility to log in wasm/browser"
readme = "readme.md"
keywords = ["wasm"]

[lints]
workspace = true

[dependencies]

mod_interface = { workspace = true }
browser_log = { workspace = true }

# xxx : introduce features
# xxx : introduce features: enabled, default, full
