[package]
name = "browser_input"
version = "0.1.0"
edition = "2024"

[dependencies]
minwebgl = { workspace = true, features = ["math"] }
web-sys = { workspace = true, features = [
  "MouseEvent",
  "KeyboardEvent",
  "HtmlInputElement",
] }
strum = { version = "0.27.1", features = ["derive"] }

[lints]
workspace = true
