[package]
name = "hexagonal_grid"
version = "0.1.0"
edition = "2024"

[dependencies]
pathfinding = "4.14.0"
minwebgl = { workspace = true, features = [ "math" ] }
web-sys = { workspace = true, features = [ "DomRect", "MouseEvent" ] }
derive_tools = { workspace = true }
tiles_tools = { workspace = true }
