[package]
name = "hexagonal_grid"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.1"
minwebgl = { workspace = true, features = ["math"] }
web-sys = { workspace = true, features = ['DomRect', 'MouseEvent'] }
