[package]
name = "hexagonal_grid"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.1"
minwebgl = { workspace = true, features = [ "math", "web", "log" ] }
web-sys = { workspace = true, features = [ "DomRect", "MouseEvent" ] }
derive_tools = { workspace = true }
tiles_tools = { workspace = true }
