edition = "2024"

unstable_features = true
max_width = 120
hard_tabs = false
tab_spaces = 2
spaces_around_ranges = true
use_small_heuristics = "Off"
space_before_colon = true
space_after_colon = true
spaces_within_parens_and_brackets = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysSameLine"
# control_brace_style = "AlwaysNextLine"
# brace_style = "AlwaysNextLine"
# fn_single_line = false
