[package]
name = "minwebgpu__"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"

[dependencies]
tobj =  { workspace = true }

[dependencies.minwebgpu]
workspace = true
features = [
    'future',
    'file',
    'objModel'
]

