[package]
name = "ndarray_cg"
version = "0.3.0"
edition = "2021"
rust-version = "1.75.0"
authors = ["Kostiantyn Mysnyk <wandalen@obox.systems>"]
license = "MIT"
repository = "https://github.com/Wandalen/cgtools"
homepage = "https://github.com/Wandalen/cgtools/tree/master/module/math/ndarray_cg"
documentation = "https://docs.rs/ndarray_cg"
readme = "readme.md"
description = "High-performance computer graphics mathematics library based on ndarray with vectors, matrices, and transformations"
keywords = ["math", "computer-graphics", "ndarray", "linear-algebra", "vectors"]
categories = ["mathematics", "graphics", "game-development", "science"]
include = [
    "src/**/*",
    "tests/**/*",
    "Cargo.toml",
    "readme.md",
    "license*",
    "changelog*",
]

[lints]
workspace = true

# [lints.rust]
# # Encourages documentation for public items.
# missing_docs = "warn" # qqq : uncomment please
# # Suggests implementing Debug for public types.
# missing_debug_implementations = "warn" # qqq : uncomment please

[features]

enabled = [
  "dep:ndarray",
  "dep:num-traits",
  "dep:asbytes",
  "dep:mod_interface",
  "dep:mdmath_core",
  "dep:derive_tools",
]
default = [
  "enabled",
]
full = [
  "default",
]

[dependencies]
ndarray = { workspace = true, optional = true }
num-traits = { workspace = true, optional = true }
# bytemuck = { workspace = true, optional = true }
asbytes = { workspace = true, optional = true }
mod_interface = { workspace = true, optional = true }
derive_tools = { workspace = true, optional = true }
mdmath_core = { workspace = true, optional = true, features = [ "index", "float", "arithmetics", "approx", "general" ] }
# approx = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }

# Metadata for crates.io
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
default-target = "x86_64-unknown-linux-gnu"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "wasm32-unknown-unknown",
]

# Cargo.toml maintenance metadata
[package.metadata.release]
pre-release-replacements = [
    { file = "readme.md", search = "ndarray_cg = \"[0-9.]+\"", replace = "ndarray_cg = \"{{version}}\"" },
    { file = "changelog.md", search = "## Unreleased", replace = "## Unreleased\n\n## {{version}} - {{date}}" },
]
