[package]
name = "embroidery_tools"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
authors = ["Kostiantyn Mysnyk <wandalen@obox.systems>"]
license = "MIT"
repository = "https://github.com/Wandalen/cgtools"
homepage = "https://github.com/Wandalen/cgtools/tree/master/module/helper/embroidery_tools"
documentation = "https://docs.rs/embroidery_tools"
description = "Tools for handling embroidery patterns, formats, and operations with PES/PEC file support"
readme = "readme.md"
keywords = ["embroidery", "patterns", "pes", "pec", "textile"]
categories = ["parsing", "graphics", "data-structures", "multimedia"]
include = [
    "src/**/*",
    "test_files/**/*",
    "tests/**/*",
    "Cargo.toml",
    "readme.md",
    "license*",
    "changelog*",
]

[lints]
workspace = true

[features]
default = ["enabled"]

# Core embroidery file processing
enabled = [
    "dep:mod_interface",
    "dep:byteorder",
    "dep:itertools",
    "dep:error_tools",
]

# Full feature set with random generation
full = ["enabled", "random"]

# Random pattern generation
random = ["enabled", "dep:rand"]

[dependencies]
mod_interface = { workspace = true, optional = true }
byteorder = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }
error_tools = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
test_tools = { workspace = true }

# Metadata for crates.io
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
default-target = "x86_64-unknown-linux-gnu"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "wasm32-unknown-unknown",
]

# Cargo.toml maintenance metadata
[package.metadata.release]
pre-release-replacements = [
    { file = "readme.md", search = "embroidery_tools = \"[0-9.]+\"", replace = "embroidery_tools = \"{{version}}\"" },
    { file = "changelog.md", search = "## Unreleased", replace = "## Unreleased\n\n## {{version}} - {{date}}" },
]
