[package]
name = "minwebgl_text_msdf"
version = "0.1.0"
edition = "2021"
authors = [ 
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Avramenko Yevhenii <yevhenii.av@obox.systems>" 
]

[dependencies]
minwebgl = { workspace = true, features = [ "future", "file" ] }
serde = { version = "1.0.215", features = [ "derive" ] }
serde_json = "1.0.133"

glam = "0.29.2"
bytemuck = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
  'KeyboardEvent',
]